[env]
RUSTFLAGS = "-C debuginfo=0 -C target-cpu=native -C opt-level=3 -C codegen-units=1 -C strip=symbols -C panic=abort -C linker=clang -C embed-bitcode=yes -C link-args=-fPIC -lffms2"

[build]
rustflags = [
    "-C", "debuginfo=0",
    "-C", "target-cpu=native",
    "-C", "opt-level=3",
    "-C", "codegen-units=1",
    "-C", "strip=symbols",
    "-C", "panic=abort",
    "-C", "linker=clang",
    "-C", "embed-bitcode=yes",
    "-C", "link-args=-fPIC",
    "-lffms2",
]
