[env]
RUSTFLAGS = "-C debuginfo=0 -C opt-level=3 -C codegen-units=1 -C strip=symbols -C panic=abort -C lto=fat -C embed-bitcode=yes -Z dylib-lto -Z panic_abort_tests -C target-feature=+crt-static -C link-arg=/LTCG"

[build]
rustflags = [
    "-C", "debuginfo=0",
    "-C", "opt-level=3",
    "-C", "codegen-units=1",
    "-C", "strip=symbols",
    "-C", "panic=abort",
    "-C", "lto=fat",
    "-C", "embed-bitcode=yes",
    "-Z", "dylib-lto",
    "-Z", "panic_abort_tests",
    "-C", "target-feature=+crt-static",
    "-C", "link-arg=/LTCG",
]
